services:
  cortes-gui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./input_videos:/app/input_videos
      - ./output_videos:/app/output_videos
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.headless true --server.port=8501
